import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import type { ModelConnection, ModelRole, ModelRoute, NodalStudioPlatform } from "../platform";

const roles: ModelRole[] = ["analysis", "explanation", "embedding"];

export function ModelConnectionsSettings({ platform }: { platform: NodalStudioPlatform }) {
  const [name, setName] = useState("");
  const [endpoint, setEndpoint] = useState("");
  const [model, setModel] = useState("");
  const [secret, setSecret] = useState<Record<string, string>>({});
  const [testStatus, setTestStatus] = useState<Record<string, string>>({});
  const stored = useQuery({ queryKey: ["model-connections"], queryFn: async () => { const [connections, routes, usage] = await Promise.all([platform.listModelConnections(), platform.getModelRoutes(), platform.listAiUsageEvents()]); return { connections, routes, usage }; } });
  const connections: ModelConnection[] = stored.data?.connections ?? [];
  const routes: ModelRoute[] = stored.data?.routes ?? [];
  const reload = async () => { await stored.refetch(); };
  const create = async (offline: boolean) => {
    const connection: ModelConnection = { id: crypto.randomUUID(), name: name || (offline ? "Offline Analyzer" : model || "Model Connection"), provider: offline ? "offline" : "openAiCompatible", endpoint: offline ? null : endpoint, model: offline ? "offline-analyzer" : model, credentialRef: null, capabilities: { chat: true, structuredOutput: true, toolCalling: !offline, embeddings: !offline, codeAnalysis: !offline, local: offline || endpoint.startsWith("http://127.0.0.1") || endpoint.startsWith("http://localhost"), maxContextTokens: null }, privacy: { allowUncommittedCode: false, allowSourceExcerpts: true, remote: !offline }, enabled: true };
    await platform.saveModelConnection(connection); setName(""); setEndpoint(""); setModel(""); await reload();
  };
  return <div className="model-connections-settings">
    <h3>Model Connections</h3><p>Reusable providers for code analysis, explanations, and embeddings. Credentials stay in Keychain.</p>
    <div className="model-connection-create"><input aria-label="Connection name" value={name} onChange={(event) => setName(event.target.value)} placeholder="Connection name" /><input aria-label="Model endpoint" value={endpoint} onChange={(event) => setEndpoint(event.target.value)} placeholder="https://… or http://localhost…" /><input aria-label="Model name" value={model} onChange={(event) => setModel(event.target.value)} placeholder="Model" /><button type="button" onClick={() => void create(false)} disabled={!endpoint || !model}>Add connection</button><button type="button" onClick={() => void create(true)}>Add offline</button></div>
    {connections.map((connection) => { const routed = routes.some((route) => route.primaryConnectionId === connection.id || route.fallbackConnectionIds.includes(connection.id)); return <article key={connection.id}><header><strong>{connection.name}</strong><span>{connection.provider} · {connection.capabilities.local ? "Local" : "Remote"}</span><button type="button" onClick={() => void platform.testModelConnection(connection.id).then((result) => setTestStatus({ ...testStatus, [connection.id]: result.networkUsed ? "Connected" : "Ready · no network" }), () => setTestStatus({ ...testStatus, [connection.id]: "Test failed" }))}>Test</button><button type="button" onClick={() => void platform.saveModelConnection({ ...connection, enabled: !connection.enabled }).then(reload)}>{connection.enabled ? "Disable" : "Enable"}</button><button type="button" disabled={routed} title={routed ? "Clear or replace its task routes first" : "Delete connection"} onClick={() => void platform.deleteModelConnection(connection.id).then(reload)}>Delete</button></header>{testStatus[connection.id] ? <p className="setting-inline-note">{testStatus[connection.id]}</p> : null}{connection.provider !== "offline" ? <div className="secret-setting"><input aria-label={`API key for ${connection.name}`} type="password" value={secret[connection.id] ?? ""} onChange={(event) => setSecret({ ...secret, [connection.id]: event.target.value })} placeholder={connection.credentialRef ? "Stored in Keychain" : "API key"} /><button type="button" disabled={!secret[connection.id]} onClick={() => void platform.saveModelCredential(connection.id, secret[connection.id] ?? "").then(() => { setSecret({ ...secret, [connection.id]: "" }); return reload(); })}>Save key</button></div> : null}</article>; })}
    {connections.map((connection) => <div className="model-privacy" key={`privacy-${connection.id}`}><strong>{connection.name} privacy</strong><label><input type="checkbox" checked={connection.privacy.allowSourceExcerpts} onChange={(event) => void platform.saveModelConnection({ ...connection, privacy: { ...connection.privacy, allowSourceExcerpts: event.target.checked } }).then(reload)} />Allow selected source excerpts</label><label><input type="checkbox" checked={connection.privacy.allowUncommittedCode} onChange={(event) => void platform.saveModelConnection({ ...connection, privacy: { ...connection.privacy, allowUncommittedCode: event.target.checked } }).then(reload)} />Allow uncommitted code</label></div>)}
    <h3>Task Routing</h3>{roles.map((role) => { const route = routes.find((item) => item.role === role); const save = (primaryConnectionId: string, fallbackConnectionIds: string[]) => void platform.saveModelRoute({ role, primaryConnectionId, fallbackConnectionIds }).then(reload); return <div className="model-route" key={role}><label className="setting-row"><span><strong>{role[0].toUpperCase() + role.slice(1)} Model</strong></span><select value={route?.primaryConnectionId ?? ""} onChange={(event) => { if (event.target.value) save(event.target.value, route?.fallbackConnectionIds ?? []); }}><option value="">Not configured</option>{connections.filter((connection) => connection.enabled).map((connection) => <option key={connection.id} value={connection.id}>{connection.name}</option>)}</select></label><label className="setting-row"><span><strong>Fallback</strong><small>Never expands capability or privacy permissions.</small></span><select value={route?.fallbackConnectionIds[0] ?? ""} disabled={!route} onChange={(event) => { if (route) save(route.primaryConnectionId, event.target.value ? [event.target.value] : []); }}><option value="">Disabled</option>{connections.filter((connection) => connection.enabled && connection.id !== route?.primaryConnectionId).map((connection) => <option key={connection.id} value={connection.id}>{connection.name}</option>)}</select></label>{route ? <button type="button" onClick={() => void platform.deleteModelRoute(role).then(reload)}>Clear route</button> : null}</div>; })}
    <h3>Usage and diagnostics</h3>{stored.data?.usage.length ? <ol className="model-usage-list">{stored.data.usage.slice(0, 10).map((event) => <li key={event.id}><strong>{event.role} · {event.model}</strong><span>{event.status}{event.fallbackFrom ? " · fallback" : ""}</span><small>{new Date(event.completedAt).toLocaleString()} · {event.fileCount} files · {event.snippetCount} snippets</small></li>)}</ol> : <p>No model calls recorded. Prompts and source code are not stored in diagnostics.</p>}
  </div>;
}
