CREATE SCHEMA app;

CREATE TYPE app.order_status AS ENUM ('draft', 'paid', 'cancelled');

CREATE TABLE app.users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    display_name VARCHAR(120),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT users_email_unique UNIQUE (email)
);

COMMENT ON TABLE app.users IS 'Application user accounts';
COMMENT ON COLUMN app.users.email IS 'Canonical login email';

CREATE TABLE app.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    status app.order_status NOT NULL DEFAULT 'draft',
    total NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT orders_total_nonnegative CHECK (total >= 0),
    CONSTRAINT orders_user_fk
        FOREIGN KEY (user_id)
        REFERENCES app.users (id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX orders_active_user_idx
    ON app.orders USING btree (user_id, created_at DESC)
    WHERE status <> 'cancelled';

CREATE TABLE app.order_items (
    order_id BIGINT NOT NULL,
    line_number INTEGER NOT NULL,
    sku TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    PRIMARY KEY (order_id, line_number),
    CONSTRAINT order_items_quantity_positive CHECK (quantity > 0),
    CONSTRAINT order_items_order_fk
        FOREIGN KEY (order_id)
        REFERENCES app.orders (id)
        ON DELETE CASCADE
);

CREATE VIEW app.order_totals AS
SELECT user_id, count(*) AS order_count, sum(total) AS lifetime_total
FROM app.orders
GROUP BY user_id;

CREATE MATERIALIZED VIEW app.daily_order_totals AS
SELECT created_at::date AS order_date, sum(total) AS daily_total
FROM app.orders
GROUP BY created_at::date
WITH NO DATA;

