[package]
name = "project-scanner"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
hex.workspace = true
project-model = { path = "../project-model" }
sha2.workspace = true
thiserror.workspace = true

[dev-dependencies]
uuid.workspace = true

[lints]
workspace = true

[[bench]]
name = "scan_10k"
harness = false
